name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master  # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # ou la version que vous utilisez

      - name: Install dependencies
        run: |
          cd website  # ou le dossier où se trouve votre projet Docusaurus
          npm install

      - name: Build Docusaurus
        run: |
          cd website
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build